import {
  Project,
  Expense,
  CustodyRecord,
  User,
  AppSettings,
  SupportTicket,
  CustomRole,
  WorkflowStage
} from '../types';

export const INITIAL_ROLES: CustomRole[] = [
  {
    id: 'role_admin',
    name: 'مدير تنفيذي أو مدير عام / إدارة عليا',
    description: 'المتحكم الكامل في النظام وصاحب الصلاحيات السيادية؛ تشمل الاعتماد النهائي، تعديل الأدوار والشاشات، وإدارة السيولة والمشاريع والمستخدمين.',
    color: 'emerald',
    badgeColor: 'bg-emerald-50 text-emerald-700 border-emerald-300 dark:bg-emerald-950/40 dark:text-emerald-400 dark:border-emerald-800',
    isSystem: true,
    permissions: {
      allowedScreens: ['dashboard', 'expenses', 'approvals', 'custodies', 'projects', 'supervisors', 'reports', 'settings', 'support'],
      canViewAllProjects: true,
      canViewAllExpenses: true,
      canViewFinancialReports: true,
      canViewCustodies: true,
      canViewTeamMembers: true,
      canCreateExpense: true,
      canEditExpense: true,
      canDeleteExpense: true,
      expenseEditGraceMinutes: 9999, // غير مقيد بزمن محدد
      canManageCustody: true,
      canManageProjects: true,
      canApproveAsSupervisor: true,
      canApproveAsProjectManager: true,
      canApproveAsAccountant: true,
      canExportToExternalERP: true,
      canApproveAsManagement: true,
      canBatchApprove: true,
      canManageRolesAndPermissions: true,
      canConfigureWorkflow: true,
      canExportExcelAndBackup: true,
    }
  },
  {
    id: 'role_accountant',
    name: 'محاسب مالي',
    description: 'تدقيق الضرائب والفواتير وتوليد قيود اليومية والترحيل لبرامج المحاسبة الخارجية ومراجعة بنود المصروفات وحركات العهد.',
    color: 'blue',
    badgeColor: 'bg-blue-50 text-blue-700 border-blue-300 dark:bg-blue-950/40 dark:text-blue-400 dark:border-blue-800',
    isSystem: true,
    permissions: {
      allowedScreens: ['dashboard', 'expenses', 'approvals', 'custodies', 'projects', 'reports', 'support'],
      canViewAllProjects: true,
      canViewAllExpenses: true,
      canViewFinancialReports: true,
      canViewCustodies: true,
      canViewTeamMembers: false,
      canCreateExpense: false,
      canEditExpense: false,
      canDeleteExpense: false,
      expenseEditGraceMinutes: 0,
      canManageCustody: true,
      canManageProjects: false,
      canApproveAsSupervisor: false,
      canApproveAsProjectManager: false,
      canApproveAsAccountant: true,
      canExportToExternalERP: true,
      canApproveAsManagement: false,
      canBatchApprove: true,
      canManageRolesAndPermissions: false,
      canConfigureWorkflow: false,
      canExportExcelAndBackup: true,
    }
  },
  {
    id: 'role_supervisor',
    name: 'مشرف موقع',
    description: 'تسجيل المصروفات اليومية مع التقاط البصمة الجغرافية وصور الفواتير وإدارة العهدة الميدانية ومراجعة واعتماد المرحلة الأولى للمصروفات.',
    color: 'amber',
    badgeColor: 'bg-amber-50 text-amber-700 border-amber-300 dark:bg-amber-950/40 dark:text-amber-400 dark:border-amber-800',
    isSystem: true,
    permissions: {
      allowedScreens: ['dashboard', 'expenses', 'approvals', 'reports', 'support'],
      canViewAllProjects: false,
      canViewAllExpenses: false,
      canViewFinancialReports: false,
      canViewCustodies: false,
      canViewTeamMembers: false,
      canCreateExpense: true,
      canEditExpense: true,
      canDeleteExpense: false,
      expenseEditGraceMinutes: 30, // مهلة 30 دقيقة رقابية
      canManageCustody: false,
      canManageProjects: false,
      canApproveAsSupervisor: true,
      canApproveAsProjectManager: true,
      canApproveAsAccountant: false,
      canExportToExternalERP: false,
      canApproveAsManagement: false,
      canBatchApprove: false,
      canManageRolesAndPermissions: false,
      canConfigureWorkflow: false,
      canExportExcelAndBackup: false,
    }
  }
];

export const INITIAL_WORKFLOW_STAGES: WorkflowStage[] = [
  {
    id: 'stage_supervisor',
    title: 'المرحلة 1: مراجعة المصروف والاعتماد للمشرف',
    subtitle: 'التحقق الميداني ومطابقة الأعمال المنجزة مع الفواتير',
    description: 'مراجعة مشرف الموقع للفاتورة ومطابقة الأعمال المنجزة ميدانياً',
    order: 1,
    requiredRoleId: 'role_supervisor',
    requiredRoleName: 'مشرف موقع',
    roleId: 'role_supervisor',
    requiresExternalErpPosting: false,
    allowReject: true,
    isActive: true,
    iconName: 'HardHat'
  },
  {
    id: 'stage_accountant',
    title: 'المرحلة 2: مراجعة وترحيل المحاسب المالي',
    subtitle: 'تدقيق الضريبة وتوليد القيد والإدخال على برنامج المحاسبة الخارجي (ERP)',
    description: 'تدقيق المحاسب المالي والضريبة وترحيل القيد للبرنامج المحاسبي',
    order: 2,
    requiredRoleId: 'role_accountant',
    requiredRoleName: 'محاسب مالي',
    roleId: 'role_accountant',
    requiresExternalErpPosting: true,
    allowReject: true,
    isActive: true,
    iconName: 'FileSpreadsheet'
  },
  {
    id: 'stage_management',
    title: 'المرحلة 3: اعتماد الإدارة العليا',
    subtitle: 'الاعتماد النهائي التنفيذي وإقفال وخصم السند رسمياً من رصيد العهدة',
    description: 'الاعتماد النهائي من المدير التنفيذي أو العام والخصم من رصيد العهدة',
    order: 3,
    requiredRoleId: 'role_admin',
    requiredRoleName: 'مدير تنفيذي أو مدير عام / إدارة عليا',
    roleId: 'role_admin',
    requiresExternalErpPosting: false,
    allowReject: true,
    isActive: true,
    iconName: 'ShieldCheck'
  }
];

export const INITIAL_USERS: User[] = [
  {
    id: 'USR-01',
    email: '2030m.mansour@gmail.com',
    username: 'm.mansour',
    password: 'Password@2026',
    name: 'م. منصور (المدير التنفيذي)',
    role: 'مدير تنفيذي أو مدير عام / إدارة عليا',
    roleId: 'role_admin',
    phone: '+966 50 123 4567',
    updateMode: 'ALL_CHANGES',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'USR-02',
    email: 'pm.khaled@project-sic.sa',
    username: 'khaled.pm',
    password: 'Password@2026',
    name: 'م. خالد السبيعي (مدير تنفيذي)',
    role: 'مدير تنفيذي أو مدير عام / إدارة عليا',
    roleId: 'role_admin',
    phone: '+966 50 888 7766',
    updateMode: 'ALL_CHANGES',
    assignedProjects: ['project-10', 'PRJ-01', 'PRJ-02'],
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'USR-03',
    email: 'accountant@project-sic.sa',
    username: 'sami.accountant',
    password: 'Password@2026',
    name: 'أ. سامي الزهراني (المحاسب المالي)',
    role: 'محاسب مالي',
    roleId: 'role_accountant',
    phone: '+966 55 987 6543',
    updateMode: 'UPDATES_ONLY',
    assignedProjects: ['project-10', 'PRJ-01', 'PRJ-02', 'PRJ-03'],
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'USR-04',
    email: 'supervisor.ahmed@project-sic.sa',
    username: 'ahmed.supervisor',
    password: 'Password@2026',
    name: 'م. أحمد خالد (مشرف الموقع)',
    role: 'مشرف موقع',
    roleId: 'role_supervisor',
    phone: '+966 54 321 0987',
    updateMode: 'ALL_CHANGES',
    assignedProjects: ['project-10', 'PRJ-01', 'PRJ-02'],
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'USR-05',
    email: 'supervisor.tariq@project-sic.sa',
    username: 'tariq.supervisor',
    password: 'Password@2026',
    name: 'م. طارق العمري (مشرف الموقع)',
    role: 'مشرف موقع',
    roleId: 'role_supervisor',
    phone: '+966 56 444 3322',
    updateMode: 'ALL_CHANGES',
    assignedProjects: ['project-10', 'PRJ-02', 'PRJ-03'],
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
  }
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'project-10',
    code: 'project-10',
    name: 'مشروع 10 (Project 10)',
    status: 'جاري',
    emails: '2030m.mansour@gmail.com, supervisor.ahmed@project-sic.sa, accountant@project-sic.sa, pm.khaled@project-sic.sa, supervisor.tariq@project-sic.sa',
    assignedUserIds: ['USR-01', 'USR-02', 'USR-03', 'USR-04', 'USR-05'],
    assignedEmails: ['2030m.mansour@gmail.com', 'pm.khaled@project-sic.sa', 'accountant@project-sic.sa', 'supervisor.ahmed@project-sic.sa', 'supervisor.tariq@project-sic.sa'],
    budget: 2500000,
    clientName: 'شركة المشروعات المتكاملة (العميل الرئيسي)',
    location: 'الرياض - الموقع الميداني 10',
    startDate: '2026-01-01',
    endDate: '2027-12-31',
    description: 'المشروع الرئيسي المعتمد على قاعدة بيانات Firestore السحابية (project-10).',
    createdAt: '2026-01-01',
  },
  {
    id: 'PRJ-01',
    code: 'SIC-PRJ-2026-01',
    name: 'مشروع برج الأندلس الإداري',
    status: 'جاري',
    emails: 'supervisor.ahmed@project-sic.sa, accountant@project-sic.sa, 2030m.mansour@gmail.com, pm.khaled@project-sic.sa',
    assignedUserIds: ['USR-01', 'USR-02', 'USR-03', 'USR-04'],
    assignedEmails: ['2030m.mansour@gmail.com', 'pm.khaled@project-sic.sa', 'accountant@project-sic.sa', 'supervisor.ahmed@project-sic.sa'],
    budget: 850000,
    clientName: 'شركة الأندلس القابضة',
    location: 'الرياض - حي العليا',
    startDate: '2026-01-15',
    endDate: '2026-12-30',
    description: 'أعمال التشطيبات الكهروميكانيكية والواجهات الزجاجية للبرج.',
    createdAt: '2026-01-10',
  },
  {
    id: 'PRJ-02',
    code: 'SIC-PRJ-2026-02',
    name: 'مشروع مجمع الياسمين السكني (فيلا 1-14)',
    status: 'جاري',
    emails: 'supervisor.ahmed@project-sic.sa, accountant@project-sic.sa, supervisor.tariq@project-sic.sa, pm.khaled@project-sic.sa',
    assignedUserIds: ['USR-02', 'USR-03', 'USR-04', 'USR-05'],
    assignedEmails: ['pm.khaled@project-sic.sa', 'accountant@project-sic.sa', 'supervisor.ahmed@project-sic.sa', 'supervisor.tariq@project-sic.sa'],
    budget: 1450000,
    clientName: 'مؤسسة التطوير العقاري الحديث',
    location: 'الرياض - حي الياسمين',
    startDate: '2026-02-01',
    endDate: '2027-03-30',
    description: 'بناء وتأسيس البنية التحتية والإنشاءات الخرسانية لـ 14 فيلا سكنية.',
    createdAt: '2026-01-28',
  },
  {
    id: 'PRJ-03',
    code: 'SIC-PRJ-2026-03',
    name: 'مشروع مستودعات المنطقة اللوجستية',
    status: 'جاري',
    emails: 'supervisor.tariq@project-sic.sa',
    assignedUserIds: ['USR-05'],
    assignedEmails: ['supervisor.tariq@project-sic.sa'],
    budget: 620000,
    clientName: 'شركة الإمداد السريع للتخزين',
    location: 'جدة - الخمرة الصناعية',
    startDate: '2026-03-01',
    endDate: '2026-10-15',
    description: 'تأهيل أرضيات الهياكل الفولاذية ونظام الإطفاء والسلامة المعتمد.',
    createdAt: '2026-02-15',
  },
  {
    id: 'PRJ-04',
    code: 'SIC-PRJ-2025-08',
    name: 'مشروع مجمع الروابي التجاري',
    status: 'مكتمل',
    emails: 'supervisor.ahmed@project-sic.sa',
    assignedUserIds: ['USR-04'],
    assignedEmails: ['supervisor.ahmed@project-sic.sa'],
    budget: 980000,
    clientName: 'مجموعة الروابي للاستثمار',
    location: 'الخبر - طريق الملك فهد',
    startDate: '2025-04-01',
    endDate: '2026-01-20',
    description: 'تسليم نهائي للمجمع وإغلاق الحسابات وتصفية العهد المتبقية.',
    createdAt: '2025-03-20',
  }
];

export const INITIAL_CUSTODIES: CustodyRecord[] = [
  {
    id: 'CUST-2026-01',
    supervisorEmail: 'supervisor.ahmed@project-sic.sa',
    supervisorName: 'م. أحمد خالد (مشرف الموقع)',
    amount: 50000,
    date: '2026-08-01',
    paymentMethod: 'تحويل بنكي',
    receiptNumber: 'BNK-984210',
    notes: 'دفعة عهدة تشغيلية لمشروع برج الأندلس والياسمين',
    issuedBy: '2030m.mansour@gmail.com',
    synced: true,
  },
  {
    id: 'CUST-2026-02',
    supervisorEmail: 'supervisor.ahmed@project-sic.sa',
    supervisorName: 'م. أحمد خالد (مشرف الموقع)',
    amount: 25000,
    date: '2026-08-20',
    paymentMethod: 'تحويل بنكي',
    receiptNumber: 'BNK-992340',
    notes: 'تعزيز عهدة لتغطية أجور العمالة المؤقتة ومواد العزل',
    issuedBy: '2030m.mansour@gmail.com',
    synced: true,
  },
  {
    id: 'CUST-2026-03',
    supervisorEmail: 'supervisor.tariq@project-sic.sa',
    supervisorName: 'م. طارق العمري (مشرف الميدان)',
    amount: 30000,
    date: '2026-08-10',
    paymentMethod: 'تحويل بنكي',
    receiptNumber: 'BNK-988712',
    notes: 'عهدة بدء أعمال مشروع المستودعات اللوجستية بجدة',
    issuedBy: '2030m.mansour@gmail.com',
    synced: true,
  }
];

// Helper to make timestamps around current local time
const now = new Date();
const minutesAgo = (mins: number) => new Date(now.getTime() - mins * 60 * 1000).toISOString();
const daysAgo = (days: number) => {
  const d = new Date(now.getTime() - days * 24 * 60 * 60 * 1000);
  return d.toISOString().split('T')[0];
};

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'EXP-1010',
    date: daysAgo(0),
    fingerprintTime: minutesAgo(8),
    supervisorEmail: '2030m.mansour@gmail.com',
    supervisorName: 'م. منصور (المدير التنفيذي)',
    projectId: 'project-10',
    projectName: 'مشروع 10 (Project 10)',
    category: 'مواد بناء',
    details: 'شراء مواد تأسيس وأدوات تشغيل لموقع مشروع 10 السحابي',
    amount: 5400,
    taxAmount: 810,
    invoiceNumber: 'INV-PRJ10-001',
    invoicePhoto: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&auto=format&fit=crop&q=80',
    gpsLocation: { lat: 24.7136, lng: 46.6753, address: 'موقع مشروع 10، الرياض', accuracy: 5 },
    updatedAt: minutesAgo(8),
    status: 'بانتظار الاعتماد',
    currentStageId: 'stage_supervisor',
    currentStageIndex: 0,
    supervisorApproval: 'غير معتمد',
    projectManagerApproval: 'غير معتمد',
    accountantApproval: 'غير معتمد',
    managementApproval: 'غير معتمد',
    erpPostingStatus: 'غير مرحل',
    workflowHistory: [
      {
        stageId: 'submission',
        stageTitle: 'قيد المصروف من المشرف الميداني',
        status: 'pending',
        actionByEmail: '2030m.mansour@gmail.com',
        actionByName: 'م. منصور (المدير التنفيذي)',
        actionRole: 'مدير تنفيذي أو مدير عام / إدارة عليا',
        actionTime: minutesAgo(8),
        notes: 'تم توريد المواد لموقع مشروع 10 وقيد السند على قاعدة البيانات السحابية.'
      }
    ],
    synced: true,
  },
  {
    id: 'EXP-1001',
    date: daysAgo(0),
    fingerprintTime: minutesAgo(12), // Only 12 mins ago -> editable within 30 min window!
    supervisorEmail: 'supervisor.ahmed@project-sic.sa',
    supervisorName: 'م. أحمد خالد (مشرف الموقع)',
    projectId: 'PRJ-01',
    projectName: 'مشروع برج الأندلس الإداري',
    category: 'مواد بناء',
    details: 'شراء كوابل كهربائية وأنابيب تمديد نحاسية من شركة الفنار',
    amount: 3450,
    taxAmount: 517.5,
    invoiceNumber: 'INV-ALFANAR-7782',
    invoicePhoto: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&auto=format&fit=crop&q=80',
    gpsLocation: { lat: 24.7136, lng: 46.6753, address: 'حي العليا، الرياض', accuracy: 5 },
    updatedAt: minutesAgo(12),
    status: 'بانتظار الاعتماد',
    currentStageId: 'stage_supervisor',
    currentStageIndex: 0,
    supervisorApproval: 'غير معتمد',
    projectManagerApproval: 'غير معتمد',
    accountantApproval: 'غير معتمد',
    managementApproval: 'غير معتمد',
    erpPostingStatus: 'غير مرحل',
    workflowHistory: [
      {
        stageId: 'submission',
        stageTitle: 'قيد المصروف من المشرف الميداني',
        status: 'pending',
        actionByEmail: 'supervisor.ahmed@project-sic.sa',
        actionByName: 'م. أحمد خالد (مشرف الموقع)',
        actionRole: 'مشرف موقع',
        actionTime: minutesAgo(12),
        notes: 'تم شراء المواد وتوريدها لموقع برج الأندلس مع الفاتورة الضريبية.'
      }
    ],
    synced: true,
  },
  {
    id: 'EXP-1002',
    date: daysAgo(0),
    fingerprintTime: minutesAgo(24), // 24 mins ago -> editable
    supervisorEmail: 'supervisor.ahmed@project-sic.sa',
    supervisorName: 'م. أحمد خالد (مشرف الموقع)',
    projectId: 'PRJ-02',
    projectName: 'مشروع مجمع الياسمين السكني (فيلا 1-14)',
    category: 'عمالة',
    details: 'يوميات عمالة صب الخرسانة المسلحة للسقف الأرضي (7 عمال)',
    amount: 1750,
    taxAmount: 0,
    invoiceNumber: 'RCP-LABOR-082',
    invoicePhoto: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=800&auto=format&fit=crop&q=80',
    gpsLocation: { lat: 24.8198, lng: 46.6432, address: 'حي الياسمين، الرياض', accuracy: 8 },
    updatedAt: minutesAgo(24),
    status: 'بانتظار الاعتماد',
    currentStageId: 'stage_supervisor',
    currentStageIndex: 0,
    supervisorApproval: 'غير معتمد',
    projectManagerApproval: 'غير معتمد',
    accountantApproval: 'غير معتمد',
    managementApproval: 'غير معتمد',
    erpPostingStatus: 'غير مرحل',
    workflowHistory: [
      {
        stageId: 'submission',
        stageTitle: 'قيد المصروف من المشرف الميداني',
        status: 'pending',
        actionByEmail: 'supervisor.ahmed@project-sic.sa',
        actionByName: 'م. أحمد خالد (مشرف الموقع)',
        actionRole: 'مشرف موقع',
        actionTime: minutesAgo(24),
        notes: 'سداد أجور عمالة الصب نقداً بموقع فيلا 3 و 4.'
      }
    ],
    synced: true,
  },
  {
    id: 'EXP-1003',
    date: daysAgo(1),
    fingerprintTime: minutesAgo(180), // 3 hours ago
    supervisorEmail: 'supervisor.ahmed@project-sic.sa',
    supervisorName: 'م. أحمد خالد (مشرف الموقع)',
    projectId: 'PRJ-01',
    projectName: 'مشروع برج الأندلس الإداري',
    category: 'مصروفات بفواتير ضريبية',
    details: 'تأجير رافعة شوكية ومولد كهرباء كاتم للصوت لمدة 3 أيام',
    amount: 4200,
    taxAmount: 630,
    invoiceNumber: 'INV-RENT-5541',
    invoicePhoto: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&auto=format&fit=crop&q=80',
    gpsLocation: { lat: 24.7140, lng: 46.6760, address: 'موقع برج الأندلس، الرياض', accuracy: 6 },
    updatedAt: minutesAgo(180),
    status: 'بانتظار مراجعة وترحيل المحاسب المالي',
    currentStageId: 'stage_accountant',
    currentStageIndex: 1,
    supervisorApproval: 'تم اعتماد المشرف',
    supervisorNotes: 'تمت مطابقة ساعات تشغيل المعدات بالموقع واعتماد الفاتورة.',
    supervisorActionTime: minutesAgo(120),
    projectManagerApproval: 'تم اعتماد مدير المشروع',
    projectManagerNotes: 'تمت مطابقة ساعات تشغيل المعدات بالموقع واعتماد الفاتورة.',
    projectManagerActionTime: minutesAgo(120),
    projectManagerName: 'م. خالد السبيعي',
    accountantApproval: 'غير معتمد',
    managementApproval: 'غير معتمد',
    erpPostingStatus: 'بانتظار الترحيل',
    workflowHistory: [
      {
        stageId: 'submission',
        stageTitle: 'قيد المصروف من المشرف الميداني',
        status: 'approved',
        actionByEmail: 'supervisor.ahmed@project-sic.sa',
        actionByName: 'م. أحمد خالد (مشرف الموقع)',
        actionRole: 'مشرف موقع',
        actionTime: minutesAgo(180)
      },
      {
        stageId: 'stage_pm',
        stageTitle: 'اعتماد مدير المشروع',
        status: 'approved',
        actionByEmail: 'pm.khaled@project-sic.sa',
        actionByName: 'م. خالد السبيعي (مدير مشاريع)',
        actionRole: 'مدير مشروع',
        actionTime: minutesAgo(120),
        notes: 'تم التحقق من تشغيل الرافعة والمولد بالموقع والاعتماد.'
      }
    ],
    synced: true,
  },
  {
    id: 'EXP-1004',
    date: daysAgo(2),
    fingerprintTime: minutesAgo(1440),
    supervisorEmail: 'supervisor.ahmed@project-sic.sa',
    supervisorName: 'م. أحمد خالد (مشرف الموقع)',
    projectId: 'PRJ-02',
    projectName: 'مشروع مجمع الياسمين السكني (فيلا 1-14)',
    category: 'مقاولين',
    details: 'دفعة مقاول أعمال الحدادة المسلحة لفيلا 3 و 4',
    amount: 8500,
    taxAmount: 1275,
    invoiceNumber: 'CTR-STEEL-109',
    invoicePhoto: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80',
    gpsLocation: { lat: 24.8210, lng: 46.6450, address: 'موقع الياسمين، الرياض', accuracy: 4 },
    updatedAt: minutesAgo(1440),
    status: 'بانتظار اعتماد الإدارة العليا',
    currentStageId: 'stage_management',
    currentStageIndex: 2,
    supervisorApproval: 'تم اعتماد المشرف',
    supervisorNotes: 'الأعمال مطابقة لدفتر الشروط والمواصفات.',
    supervisorActionTime: minutesAgo(1350),
    projectManagerApproval: 'تم اعتماد مدير المشروع',
    projectManagerNotes: 'تم استلام حدادة الفلل والمطابقة مع المخططات.',
    projectManagerActionTime: minutesAgo(1350),
    projectManagerName: 'م. خالد السبيعي',
    accountantApproval: 'تم الاعتماد',
    accountantNotes: 'تمت مراجعة الفاتورة الضريبية وتوليد قيد اليومية بالبرنامج الخارجي.',
    accountantActionTime: minutesAgo(1300),
    accountantName: 'أ. سامي الزهراني',
    erpPostingStatus: 'تم الترحيل للبرنامج المحاسبي',
    erpSystemName: 'قيود (Qoyod)',
    erpReferenceNumber: 'JV-2026-8819',
    erpPostedDate: daysAgo(2),
    managementApproval: 'غير معتمد',
    managementNotes: '',
    workflowHistory: [
      {
        stageId: 'submission',
        stageTitle: 'قيد المصروف من المشرف الميداني',
        status: 'approved',
        actionByEmail: 'supervisor.ahmed@project-sic.sa',
        actionByName: 'م. أحمد خالد',
        actionRole: 'مشرف موقع',
        actionTime: minutesAgo(1440)
      },
      {
        stageId: 'stage_supervisor',
        stageTitle: 'المرحلة 1: مراجعة المصروف والاعتماد للمشرف',
        status: 'approved',
        actionByEmail: 'supervisor.ahmed@project-sic.sa',
        actionByName: 'م. أحمد خالد (مشرف الموقع)',
        actionRole: 'مشرف موقع',
        actionTime: minutesAgo(1350),
        notes: 'الأعمال مطابقة لدفتر الشروط والمواصفات.'
      },
      {
        stageId: 'stage_accountant',
        stageTitle: 'المرحلة 2: مراجعة وترحيل المحاسب المالي',
        status: 'approved',
        actionByEmail: 'accountant@project-sic.sa',
        actionByName: 'أ. سامي الزهراني',
        actionRole: 'محاسب مالي',
        actionTime: minutesAgo(1300),
        erpSystemName: 'قيود (Qoyod)',
        erpReferenceNumber: 'JV-2026-8819',
        notes: 'تم قيد السند في برنامج قيود برقم JV-2026-8819.'
      }
    ],
    synced: true,
  },
  {
    id: 'EXP-1005',
    date: daysAgo(3),
    fingerprintTime: minutesAgo(2880),
    supervisorEmail: 'supervisor.tariq@project-sic.sa',
    supervisorName: 'م. طارق العمري (مشرف الميدان)',
    projectId: 'PRJ-03',
    projectName: 'مشروع مستودعات المنطقة اللوجستية',
    category: 'نقل ومحروقات',
    details: 'تعبئة ديزل للمعدات ونقل عينات التربة لمختبر الجودة',
    amount: 1850,
    taxAmount: 277.5,
    invoiceNumber: 'INV-FUEL-990',
    invoicePhoto: 'https://images.unsplash.com/photo-1527018601619-a508a2be00cd?w=800&auto=format&fit=crop&q=80',
    gpsLocation: { lat: 21.3891, lng: 39.2415, address: 'المنطقة اللوجستية، جدة', accuracy: 10 },
    updatedAt: minutesAgo(2880),
    status: 'معتمد',
    projectManagerApproval: 'تم اعتماد مدير المشروع',
    accountantApproval: 'تم الاعتماد',
    erpPostingStatus: 'تم الترحيل للبرنامج المحاسبي',
    erpSystemName: 'دفترة (Daftra)',
    erpReferenceNumber: 'JV-DFT-4102',
    managementApproval: 'تم اعتماد الادارة',
    workflowHistory: [
      {
        stageId: 'stage_accountant',
        stageTitle: 'مراجعة وترحيل المحاسب المالي',
        status: 'approved',
        actionByName: 'أ. سامي الزهراني',
        erpSystemName: 'دفترة (Daftra)',
        erpReferenceNumber: 'JV-DFT-4102',
        actionTime: minutesAgo(2800)
      }
    ],
    synced: true,
  },
  {
    id: 'EXP-1006',
    date: daysAgo(4),
    fingerprintTime: minutesAgo(4200),
    supervisorEmail: 'supervisor.tariq@project-sic.sa',
    supervisorName: 'م. طارق العمري (مشرف الميدان)',
    projectId: 'PRJ-03',
    projectName: 'مشروع مستودعات المنطقة اللوجستية',
    category: 'صيانة ومعدات',
    details: 'صيانة طارئة لماكينة لحام الهياكل وتغيير فلاتر الهواء',
    amount: 1200,
    taxAmount: 180,
    invoiceNumber: 'INV-MAINT-442',
    invoicePhoto: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    gpsLocation: { lat: 21.3895, lng: 39.2420, address: 'جدة الصناعية', accuracy: 7 },
    updatedAt: minutesAgo(4200),
    status: 'معتمد',
    projectManagerApproval: 'تم اعتماد مدير المشروع',
    accountantApproval: 'تم الاعتماد',
    erpPostingStatus: 'تم الترحيل للبرنامج المحاسبي',
    erpSystemName: 'أودو (Odoo)',
    erpReferenceNumber: 'BILL/2026/0882',
    managementApproval: 'تم اعتماد الادارة',
    workflowHistory: [
      {
        stageId: 'stage_accountant',
        stageTitle: 'مراجعة وترحيل المحاسب المالي',
        status: 'approved',
        actionByName: 'أ. سامي الزهراني',
        erpSystemName: 'أودو (Odoo)',
        erpReferenceNumber: 'BILL/2026/0882',
        actionTime: minutesAgo(4100)
      }
    ],
    synced: true,
  }
];

export const INITIAL_SETTINGS: AppSettings = {
  companyName: 'المصروفات والعهد للمشاريع',
  companySubtitle: 'منظومة إدارة العهد والمصروفات الميدانية والرقابة المالية',
  companyLogo: '',
  defaultLogoPosition: 'right',
  defaultLogoSize: 'md',
  currency: 'ريال سعودي',
  currencySymbol: 'ر.س',
  lowBalanceThreshold: 10000, // 10,000 SAR threshold from PDF spec
  editGracePeriodMinutes: 30, // 30 minutes edit rule from PDF spec
  autoGpsCapture: true,
  requireInvoicePhoto: true,
  theme: 'light',
  accentColor: 'emerald',
  compactView: false,
  enableSoundEffects: true,
  autoCloudSync: true,
  telegramRecipient: '2030m_mansour',
  whatsappRecipient: '+966 50 123 4567',
  supportPhone: '+966 50 123 4567',
  supportEmail: '2030m.mansour@gmail.com',
  dailyBackupEnabled: true,
  customCategories: [
    'عمالة',
    'مصروفات بفواتير ضريبية',
    'اعمال على',
    'مقاولين',
    'المالك',
    'رواتب',
    'نثريات ومشتريات',
    'نقل ومحروقات',
    'صيانة ومعدات',
    'مواد بناء'
  ],
  customErpSystems: [
    'Odoo ERP (أودو)',
    'SAP S/4HANA (ساب)',
    'Oracle NetSuite (أوراكل)',
    'QuickBooks Online (كويك بوكس)',
    'Daftra (دفترة)',
    'Qoyod (قيود)',
    'Al-Ameen (الأمين)',
    'SMACC (سماك)',
    'Microsoft Dynamics 365 (مايكروسوفت)'
  ],
  erpSystemName: 'Odoo ERP (أودو)',
  securityPinEnabled: false,
  securityPin: '1234',
  googleDriveAccessToken: '',
  googleDriveRefreshToken: '',
  googleDriveClientId: '',
  googleDriveClientSecret: '',
  googleDriveFolderId: '',
  pcloudPublicFolderUrl: '',
  pcloudBackupFolderUrl: '',
  pcloudAccessToken: '',
};

export const INITIAL_TICKETS: SupportTicket[] = [
  {
    id: 'TCK-101',
    title: 'طلب زيادة حد العهدة التشغيلية لمشروع الياسمين',
    category: 'استفسار مالي',
    priority: 'عاجل',
    status: 'قيد المعالجة',
    userEmail: 'supervisor.ahmed@project-sic.sa',
    userName: 'م. أحمد خالد',
    message: 'نظراً لبدء أعمال الصب للفلل 5-10، نحتاج لتعزيز العهدة بمبلغ 40,000 ريال لتسديد أجور العمالة والمواد الفورية.',
    createdAt: '2026-09-01T14:30:00.000Z',
    responses: [
      {
        id: 'RES-01',
        sender: 'م. منصور (المدير)',
        message: 'تم استلام الطلب، يرجى تصفية الفواتير المعلقة أولاً ليتم اعتماد التحويل البنكي فوراً.',
        timestamp: '2026-09-01T15:00:00.000Z',
        isAdmin: true,
      }
    ]
  },
  {
    id: 'TCK-102',
    title: 'استفسار عن طريقة التعديل بعد انقضاء 30 دقيقة',
    category: 'مشكلة فنية',
    priority: 'عادي',
    status: 'تم الحل',
    userEmail: 'supervisor.tariq@project-sic.sa',
    userName: 'م. طارق العمري',
    message: 'أدخلت مبلغ فاتورة صيانة بشكل غير دقيق ومضت 30 دقيقة على وقت البصمة.',
    createdAt: '2026-08-30T10:15:00.000Z',
    responses: [
      {
        id: 'RES-02',
        sender: 'الدعم الفني',
        message: 'وفقاً للنظام، بعد 30 دقيقة يتم قفل الفاتورة لحماية النزاهة المالية. يمكن للمحاسب أو المدير فقط تعديلها أو رفضها مع كتابة الملاحظات.',
        timestamp: '2026-08-30T11:00:00.000Z',
        isAdmin: true,
      }
    ]
  }
];
